RISK = {
 "Alaska": ["Territoires du Nord-Ouest","Alberta","Kamtchatka"],
 "Territoires du Nord-Ouest": ["Alaska","Alberta","Ontario","Groenland"],
 "Groenland": ["Territoires du Nord-Ouest","Ontario","Québec","Islande"],
 "Alberta": ["Alaska","Territoires du Nord-Ouest","Ontario","Ouest des États-Unis"],
 "Ontario": ["Territoires du Nord-Ouest","Alberta","Groenland","Québec","Ouest des États-Unis","Est des États-Unis"],
 "Québec": ["Groenland","Ontario","Est des États-Unis"],
 "Ouest des États-Unis": ["Alberta","Ontario","Est des États-Unis","Amérique centrale"],
 "Est des États-Unis": ["Ontario","Québec","Ouest des États-Unis","Amérique centrale"],
 "Amérique centrale": ["Ouest des États-Unis","Est des États-Unis","Venezuela"],
 "Venezuela": ["Amérique centrale","Pérou","Brésil"],
 "Pérou": ["Venezuela","Brésil","Argentine"],
 "Brésil": ["Venezuela","Pérou","Argentine","Afrique du Nord"],
 "Argentine": ["Pérou","Brésil"],
 "Islande": ["Groenland","Grande-Bretagne","Scandinavie"],
 "Scandinavie": ["Islande","Grande-Bretagne","Europe du Nord","Ukraine"],
 "Grande-Bretagne": ["Islande","Scandinavie","Europe du Nord","Europe de l'Ouest"],
 "Europe du Nord": ["Grande-Bretagne","Scandinavie","Ukraine","Europe du Sud","Europe de l'Ouest"],
 "Europe de l'Ouest": ["Grande-Bretagne","Europe du Nord","Europe du Sud","Afrique du Nord"],
 "Europe du Sud": ["Europe de l'Ouest","Europe du Nord","Ukraine","Moyen-Orient","Égypte","Afrique du Nord"],
 "Ukraine": ["Scandinavie","Europe du Nord","Europe du Sud","Oural","Afghanistan","Moyen-Orient"],
 "Afrique du Nord": ["Brésil","Europe de l'Ouest","Europe du Sud","Égypte","Afrique de l'Est","Congo"],
 "Égypte": ["Afrique du Nord","Europe du Sud","Moyen-Orient","Afrique de l'Est"],
 "Congo": ["Afrique du Nord","Afrique de l'Est","Afrique du Sud"],
 "Afrique de l'Est": ["Égypte","Afrique du Nord","Congo","Afrique du Sud","Madagascar","Moyen-Orient"],
 "Afrique du Sud": ["Congo","Afrique de l'Est","Madagascar"],
 "Madagascar": ["Afrique de l'Est","Afrique du Sud"],
 "Oural": ["Ukraine","Sibérie","Chine","Afghanistan"],
 "Sibérie": ["Oural","Iakoutie","Irkoutsk","Mongolie","Chine"],
 "Iakoutie": ["Sibérie","Kamtchatka","Irkoutsk"],
 "Kamtchatka": ["Iakoutie","Irkoutsk","Mongolie","Japon","Alaska"],
 "Irkoutsk": ["Sibérie","Iakoutie","Kamtchatka","Mongolie"],
 "Mongolie": ["Sibérie","Irkoutsk","Kamtchatka","Japon","Chine"],
 "Japon": ["Kamtchatka","Mongolie"],
 "Afghanistan": ["Ukraine","Oural","Chine","Inde","Moyen-Orient"],
 "Chine": ["Oural","Sibérie","Mongolie","Afghanistan","Inde","Siam"],
 "Moyen-Orient": ["Ukraine","Europe du Sud","Égypte","Afrique de l'Est","Afghanistan","Inde"],
 "Inde": ["Moyen-Orient","Afghanistan","Chine","Siam"],
 "Siam": ["Inde","Chine","Indonésie"],
 "Indonésie": ["Siam","Nouvelle-Guinée","Australie occidentale"],
 "Nouvelle-Guinée": ["Indonésie","Australie occidentale","Australie orientale"],
 "Australie occidentale": ["Indonésie","Nouvelle-Guinée","Australie orientale"],
 "Australie orientale": ["Nouvelle-Guinée","Australie occidentale"],
}
PAIRES = set()
for a, ns in RISK.items():
    for b in ns: PAIRES.add(tuple(sorted((a, b))))
